language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: AHKrtKOGnTWYoQrjl14918XK3utFQlewbOyFz489GlbdgHl9iK46P7OqteVmeMDor3TRuZWoLndI50+yq5bVHb/cPJlEq8rVMXP0MxZMHaGr1qTkDK0HoJnTwpIblJTkmvZ9txZHkqVdC+EYmyF5rx4i3SMHQfQYWuBRitRXulPmw4ueEtBhyDDDPsq5S9x4WPnwRvyAVWcAxffjdGmR+eQ2PxQS9OIbpjCYlHSH+jt8ncc2iJLfFRm8Fw9J7M4svn8WmZ9WMjmTa5RgbQZUgcj86sMnFLfL9odthhq80wK5JxYsIDlK1qIh22rK1ZaOuDztjfOisTeNM4gHPDVTYRo9a/z4tlJNLOWniBKJ9vRAcNvaeLU3fPawOxxo2dllfdyqic3n5OGxlnuYplwqLmF4PyZypDmiWLHi6HKjN1t0bzjF52amQg3bzu0q/zhK5pwIkXYSIx2lBMNcOxC4l9fNpZnxav+dSEzkN+O+d4nFK5W5jLpycYAB37TA7BUUth/Rg720Fnw0kIq3bJl0EypoHxEEQOQKKoQBpiXChq44OcAKgMoMUFuKGTMdtMIdmF4SL6qS/sTMpbKDPZzlGvuJ6JL9VUbGUpfzUEisxiZIO0LaKyC74e766KuM5uOo3vmKio//L4abXNAezO9AWoYaH5dHuCLI8RZQlE9Tcbg=
  app: damp-sands-71865
  on:
    repo: miamiyankee13/blog-api
